config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :companies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :type
  validates :name, :presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :companies
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def edit
    @type = Type.find(params[:type_id])
    @company = Company.find(params[:id])
    render :edit
  end

  def index
    @company = Company.all
    render :index
  end

  def show
    @type = Type.find(params[:type_id])
    @company = Company.find(params[:id])
    render :show
  end

  def new
    @type = Type.find(params[:type_id])
    @company = @type.companies.new
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to type_path(@company.type)
  end

  def create
    @type = Type.find(params[:type_id])
    @company = @type.companies.new(company_params)
    if @company.save
      redirect_to type_path(@company.type)
    else
      render :new
    end
  end

  def update
    @type = Type.find(params[:type_id])
    @company= Company.find(params[:id])
    if @company.update(company_params)
      redirect_to type_path(@company.type)
    else
      render :edit
    end
  end

private
  def company_params
    params.require(:company).permit(:name, :address, :phone, :website, :hours, :picture)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def edit
    @type = Type.find(params[:id])
    render :edit
  end

  def index
    @types = Type.all
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end

  def new
    @type = Type.new
    render :new
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    redirect_to types_path
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :new
    end
  end

  def update
    @type= Type.find(params[:id])
    if @type.update(type_params)
      redirect_to types_path
    else
      render :edit
    end
  end

  private
  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= render('layouts/errors', :object => @company) %>

<%= form_for [@type, @company] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :website %>
  <%= f.text_field :website %>

  <%= f.label :hours %>
  <%= f.text_field :hours %>

  <%= f.label :picture %>
  <%= f.text_field :picture %>
  <p><%= f.submit %></p>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render "form" %>

app/views/companies/new.html.erb
<h1>New company for <%= @type.name %></h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<h4><%= @company.address %></h4>
<h4><%= @company.phone %></h4>
<h4><%= @company.website %></h4>
<h4><%= @company.hours %></h4>
<h4><img src="<%= @company.picture %>" /></h4>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiAddress</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= render "layouts/errors", :object => @type %>

<%= form_for @type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/types/edit.html.erb
<h1>Edit type</h1>

<%= render "form" %>

app/views/types/index.html.erb
<h1>Types</h1>

<ul>
  <% @types.each do |type| %>
    <li><%= link_to type.name, type_path(type) %></li>
    <% end %>
</ul>

<%= link_to "New Type", new_type_path %> 

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render "form" %>

app/views/types/show.html.erb
<h1><%= @type.name %></h1>

<% if @type.companies.any? %>
  <h4>Here are the companies for this list:</h4>

  <ul>
    <% @type.companies.each do |company| %>
      <li>
        <%= link_to company.name, type_company_path(@type, company) %>  
        <%= link_to "Edit", edit_type_company_path(@type, company) %> |
        <%= link_to "Delete", type_company_path(@type, company),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no companies yet!</p>
<% end %>

<p><%= link_to "Add a company", new_type_company_path(@type) %></p>
<p><%= link_to "Delete Type", type_path(@type),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to types", types_path %></p>